export const journeyChapters = [
  { year: "2002", kicker: "Origin", title: "Born in Bangkalan.", copy: "My story started on Madura island, long before software, product meetings, or knowing that debugging would become a normal Tuesday.", accent: "#ff6543" },
  { year: "2014", kicker: "First orbit", title: "Curiosity found a direction.", copy: "At SMPN 2 Bangkalan, science became less like a school subject and more like permission to keep asking how things worked.", accent: "#a9c3ff" },
  { year: "2017", kicker: "Building momentum", title: "Science, experiments, and bigger questions.", copy: "At SMAN 1 Bangkalan I followed the science track, learned to enjoy difficult problems, and began looking beyond the obvious answer.", accent: "#c9ff57" },
  { year: "2020", kicker: "The code chapter", title: "Informatics at ITS.", copy: "I moved into Informatics at Institut Teknologi Sepuluh Nopember in Surabaya. Programming turned curiosity into something I could build and share.", accent: "#7ed9c4" },
  { year: "2022", kicker: "Learning by teaching", title: "From student to mentor and maker.", copy: "Teaching programming, administering the Algorithms and Programming Laboratory, researching, freelancing, and building for real people made the lessons stick.", accent: "#f4b36f" },
  { year: "2023", kicker: "A wider universe", title: "A double-degree journey in Eindhoven.", copy: "Fontys added Software Engineering, a new country, and a different way of collaborating to the foundation I was building at ITS.", accent: "#b69cff" },
  { year: "2024", kicker: "Into the industry", title: "ParkMundo started as a graduation internship.", copy: "I worked on multilingual products, airport parking navigation, maps, traffic data, and systems that needed to be useful outside a classroom.", accent: "#ff8a66" },
  { year: "2025", kicker: "Two graduations", title: "Sarjana Komputer and Bachelor of Science.", copy: "I completed both degrees, carrying the technical depth from ITS and the practical product focus from Fontys into the next chapter.", accent: "#d8ff87" },
  { year: "Now", kicker: "Current coordinates", title: "Software Engineer at ParkMundo.", copy: "Today I build scalable multilingual web products in Eindhoven, keep learning across the stack, and still make room for photography, running, travel, and small strange experiments.", accent: "#a9c3ff" },
] as const;
